//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleWS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name KTchanleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KTchanle", ReplyAction="*")]
        ConsoleWS.ServiceReference1.KTchanleResponse KTchanle(ConsoleWS.ServiceReference1.KTchanleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KTchanle", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleWS.ServiceReference1.KTchanleResponse> KTchanleAsync(ConsoleWS.ServiceReference1.KTchanleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KTchanleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KTchanle", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleWS.ServiceReference1.KTchanleRequestBody Body;
        
        public KTchanleRequest() {
        }
        
        public KTchanleRequest(ConsoleWS.ServiceReference1.KTchanleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KTchanleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int n;
        
        public KTchanleRequestBody() {
        }
        
        public KTchanleRequestBody(int n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KTchanleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KTchanleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleWS.ServiceReference1.KTchanleResponseBody Body;
        
        public KTchanleResponse() {
        }
        
        public KTchanleResponse(ConsoleWS.ServiceReference1.KTchanleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KTchanleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KTchanleResult;
        
        public KTchanleResponseBody() {
        }
        
        public KTchanleResponseBody(string KTchanleResult) {
            this.KTchanleResult = KTchanleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleWS.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleWS.ServiceReference1.WebService1Soap>, ConsoleWS.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleWS.ServiceReference1.KTchanleResponse ConsoleWS.ServiceReference1.WebService1Soap.KTchanle(ConsoleWS.ServiceReference1.KTchanleRequest request) {
            return base.Channel.KTchanle(request);
        }
        
        public string KTchanle(int n) {
            ConsoleWS.ServiceReference1.KTchanleRequest inValue = new ConsoleWS.ServiceReference1.KTchanleRequest();
            inValue.Body = new ConsoleWS.ServiceReference1.KTchanleRequestBody();
            inValue.Body.n = n;
            ConsoleWS.ServiceReference1.KTchanleResponse retVal = ((ConsoleWS.ServiceReference1.WebService1Soap)(this)).KTchanle(inValue);
            return retVal.Body.KTchanleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleWS.ServiceReference1.KTchanleResponse> ConsoleWS.ServiceReference1.WebService1Soap.KTchanleAsync(ConsoleWS.ServiceReference1.KTchanleRequest request) {
            return base.Channel.KTchanleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleWS.ServiceReference1.KTchanleResponse> KTchanleAsync(int n) {
            ConsoleWS.ServiceReference1.KTchanleRequest inValue = new ConsoleWS.ServiceReference1.KTchanleRequest();
            inValue.Body = new ConsoleWS.ServiceReference1.KTchanleRequestBody();
            inValue.Body.n = n;
            return ((ConsoleWS.ServiceReference1.WebService1Soap)(this)).KTchanleAsync(inValue);
        }
    }
}
